theme: jekyll-theme-cayman
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title> Flowers </title>
  <meta name="description" content="Flowers">
  <meta name="author" content="SitePoint">

  <!--<link rel="stylesheet" href="css/styles.css?v=1.0">-->
  <link rel="stylesheet" type="text/css" ref="stylesheet.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
  Welcome to the flower identification app! No matter your flower needs, this is your one stop shop. Upload an image of a flower that you see on a hike or in your garden and we will identify it for you! You can learn more about the details of the flower and how to plant it and take care of it!
  <form method="post" enctype="multipart/form-data">
    <input type="file" name="files[]" multiple />
    <input type="submit" value="Upload File" name="submit" />
  </form>
</body>
</html>
