theme: jekyll-theme-cayman
title: flowers

description: Welcome to the flower identification app! No matter your flower needs, this is your one stop shop. Upload an image of a flower that you see on a hike or in your garden and we will identify it for you! You can learn more about the details of the flower and how to plant it and take care of it!
